/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * disp_res.java
 *
 * Created on 16 Apr, 2011, 1:56:03 PM
 */

package gui;

import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author root
 */
public class disp_res extends javax.swing.JFrame {

    /** Creates new form disp_res */
    public disp_res() {
        initComponents();
        //jTextField1.setVisible(false);
        jTextField1.setEditable(false);
        String sd;
        
         int n=enters_destinatn.r_count();

         String searchText[] = new String[n];

        byte b[] = null;
        try {
            b = enters_destinatn.destIP();
        } catch (UnknownHostException ex) {
            Logger.getLogger(disp_res.class.getName()).log(Level.SEVERE, null, ex);
        }

        byte temp1[]=new byte[4];
        int a=4;
        int b1=0;
        for(int i=0;i<n;i++)
        {
            System.arraycopy(b, b1, temp1, 0, a);
            a=+4;
            b1=+4;
            InetAddress ad1 = null;
            try {
                ad1 = InetAddress.getByAddress(temp1);
            } catch (UnknownHostException ex) {
                Logger.getLogger(disp_res.class.getName()).log(Level.SEVERE, null, ex);
            }
            //searchText[i]=new String(temp1,"UTF-8");
            searchText[i]=ad1.getHostAddress();
            //System.out.println(searchText[i]);
        }

        for(int i=0;i<Home_page.n;i++)
        {
            if(Home_page.ts1[i]==0)
            {
                jTextField1.setText(searchText[i]+".txt"+"\n");
               

            }
            else
            {
                jTextField1.setText(searchText[i]+"."+ext.ext_nm+"\n");
            
            }
        }
    }








    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("Done");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jButton1)))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButton1)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        
        
        
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
       
        

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    /*public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new disp_res().setVisible(true);
            }
        });



        

    }*/


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
